--- 
- 
  become: true
  gather_facts: false
  hosts: all
- 
  list: "wget"
  name: "To list installed version of wget and rbuy on all servers"
  register: yum_output
  yum: ~
- "debug var=yum_output"
