--- 
- 
  become: true
  gather_facts: false
  hosts: all
  name: "To run command"
  tasks: 
    - 
      name: "run /etc/fstab command"
      register: his
      shell: "cat /etc/fstab"
      
    - 
      debug: 
        var: his.stdout_lines
    - 
      name: "run space check command"
      register: his
      shell: "df -h"
    - 
      debug: 
        var: his.stdout_lines
       
    -
      name: "Run yum update on the all server" 
      register: his
      shell: "yum update " 
      
    -
      debug: 
        var: his.stdout_lines
