--- 
- 
  become: true
  hosts: all
  tasks: 
    - 
      command: "cat /etc/fstab"
      name: "execute the command output for /etc/fstab"
    - 
      command: "df -h"
      name: "Execute the command output df -h "
