--- 
- 
  become: true
  gather_facts: false
  hosts: all
  name: "To run command"
  tasks: 
    - 
      name: "run yum log command"
      register: his1
      shell: "cat /etc/fstab"
    - 
      name: "run command"
      register: his
      shell: "df -h"
    - 
      debug: 
        var: his.stdout_lines
        var1: his1.stdout_lines
