--- 
- 
  become: true
  gather_facts: false
  hosts: all
  name: "To run command"
  tasks: 
    - 
      name: "run yum log command"
      shell: "yum history info > /root/last-yum-transaction.log"
    - 
      name: "run command"
      register: his
      shell: "df -h"
    - 
      debug: 
        var: his.stdout_lines
