--- 
- 
  become: true
  gather_facts: false
  hosts: all
  name: "To run command"
  tasks: 
    - 
      name: "run /etc/fstab command"
      register: his1
      shell: "cat /etc/fstab"
    - 
      name: "run command df -h "
      register: his
      shell: "df -h"
    - 
      debug: 
        var: his.stdout_linesstdout_lines
        var1: his1.stdout_linesstdout_lines
