- hosts: all
  gather_facts: true
 # become: true
 # become_method: sudo
 # become_user: root
  tasks:
    - package: "name=httpd state=present"
    - service: "name=httpd state=restarted"
    #- service: "name=httpd state=started"
