- hosts: all
  become: true
 # become_method: sudo
 # become_user: root
  tasks:
    - package: "name=vsftptd state=present"
    - service: "name=vsftptd state=stopped"
    - service: "name=vsftptd state=started"
    #- service: "name=httpd state=started"
