- hosts: all
  become: true
 # become_method: sudo
 # become_user: root
  tasks:
    - package: "name=openssh state=present"
    - service: "name=openssh state=restarted"
    #- service: "name=rsync state=started"
    #- service: "name=httpd state=started"
