- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - package: "name=httpd state=present"
    - service: "name=httpd state=status"
    #- service: "name=httpd state=started"
