--- 
- 
  become: true
  gather_facts: false
  hosts: 10.0.0.216
  name: "To run command"
  tasks: 
    -
      name: "Run yum update on the all server" 
      register: his
      shell: "yum update -y --exclude=kernel* --skip-broken " 
      
    -
      debug: 
        var: his.stdout_lines
